# Generated by Django 3.0.4 on 2020-03-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplanes', '0002_auto_20200319_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
